# Generated by Django 3.0 on 2019-12-09 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.IntegerField(unique=True)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'patients',
                'ordering': ('u_id',),
            },
        ),
    ]
