# Generated by Django 3.0 on 2019-12-09 03:42

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='lon',
        ),
        migrations.AddField(
            model_name='patient',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(default='POINT(0.0 0.0)', srid=4326),
        ),
    ]
