# Generated by Django 3.0 on 2019-12-14 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_roundrockgrid'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundrockgrid',
            name='color',
            field=models.FloatField(default=0),
        ),
    ]
